### PR TITLE
Release 2.5.1

### PR DESCRIPTION
**Pull request by mjcheetham**
**Changes:**

- Update MSAL and Avalonia to latest versions (#1640).
- Changes to release workflow to publish NuGet signing certificate (#1594, #1644, #1647).
- Updates to Managed Identity and Service Principal docs.

### CODE REVIEW

**Comment by mjcheetham** [comment]
Failing centos 8 error is related to:
https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve

cc @dscho

**Review by dscho — APPROVED** [review]
Not sure what is going on with the CentOS build, but changes look good to me!

**Comment by dscho** [comment]
> Failing centos 8 error is related to:
> https://serverfault.com/questions/1161816/mirrorlist-centos-org-no-longer-resolve
> 
> cc @dscho

Ah. That explains it all right!

**Review by vdye — APPROVED** [review]

**Comment by mjcheetham** [comment]
This version of CentOS is out of date, so I'm not going to bother investigating much further for this point-1 release. Until I have enough 'budget' to work on issues like this in GCM, I'm afraid I'll just need to merge with this check continuing to fail.

**Pull request merged**
