### PR TITLE
New release

### PR DESCRIPTION
**Pull request by ldennington**
**Changes**:
- Show the terminal/TTY based prompts when there is no desktop/GUI sessions present for GitHub (#453, #538)
- Drop "Core" from the banner asset (#534) 
- Copy Debian package files to correct directory (#545, #566, #539)
- Remove and re-add CodeQL to enable in new home (#543, #544)
- Documentation fixes (#189, #194, #412, #413, #424)
- Support for generating code coverage reports (#499)
- WSL trace template (#563)

### CODE REVIEW

**Review by mjcheetham — APPROVED** [review]
I think 538 and 539 are all the code changes in this release?

**Comment by ldennington** [comment]
> I think 538 and 539 are all the code changes in this release?

Whoops! I may have gone a little overboard. Should I remove the additional changes I added?

**Comment by mjcheetham** [comment]
> Should I remove the additional changes I added?

Not an issue really. I tend to keep the release notes only with code or behavioural changes however.

**Comment by ldennington** [comment]
> > Should I remove the additional changes I added?
> 
> Not an issue really. I tend to keep the release notes only with code or behavioural changes however.

Sounds good - noted for the future.

**Review by lisamarielfabian — COMMENTED** [review]
2

**Pull request merged**
