### PR TITLE
dependencies: update to Avalonia 11.0.4

### PR DESCRIPTION
**Pull request by de1acr0ix**
Update from Avalonia 11.0.0-preview6 to 11.0.4 and fix the codes using APIs removed since 11.0.0 release.

### CODE REVIEW

**Comment by de1acr0ix** [comment]
Please don't approve this. I found GCM actually does not exit after GitHub OAuth workflow is complete.

**Comment by mjcheetham** [comment]
Thanks for your contribution here!

> Please don't approve this. I found GCM actually does not exit after GitHub OAuth workflow is complete.

You are correct. A while ago I had been testing Avalonia using the 11.0 non-preview released bits and found the same issue. For some reason the signal to terminate the platform runloop is not working correctly, although I had confirmed it was being called. I suspect some deadlock, but never had the time to investigate much further.

We would ideally like some advice from Avalonia maintainers, on how to use Avalonia in GCM's somewhat strange scenario:

Starting as a CLI app, at some point during execution GCM _may_ wish to start up Avalonia and a UI thread. On macOS the UI thread _must_ be the entry thread, so we need to reserve that thread for Avalonia's dispatcher.

**Review by mjcheetham — CHANGES_REQUESTED** [review]
Reviewing with 'Request changes' to block merge.

**Comment by de1acr0ix** [comment]
> Thanks for your contribution here!
> 
> > Please don't approve this. I found GCM actually does not exit after GitHub OAuth workflow is complete.
> 
> You are correct. A while ago I had been testing Avalonia using the 11.0 non-preview released bits and found the same issue. For some reason the signal to terminate the platform runloop is not working correctly, although I had confirmed it was being called. I suspect some deadlock, but never had the time to investigate much further.
> 
> We would ideally like some advice from Avalonia maintainers, on how to use Avalonia in GCM's somewhat strange scenario:
> 
> Starting as a CLI app, at some point during execution GCM _may_ wish to start up Avalonia and a UI thread. On macOS the UI thread _must_ be the entry thread, so we need to reserve that thread for Avalonia's dispatcher.

I did some investigation and I now believe it is a bug of Avalonia. I have created a [PR](https://github.com/AvaloniaUI/Avalonia/pull/12579) for Avalonia and it shall fix this issue (I have verified locally on my Macbook). Once it is merged and a new release of Avalonia available, I will bump the version in this PR.

**Comment by de1acr0ix** [comment]
@mjcheetham Avalonia team really is responsive. My changes got merged and new release 11.0.4 is available. I have bumped the version in this PR and tested locally.

**Review by mjcheetham — APPROVED** [review]
@de1acr0ix thank you for fixing the Avalonia issue and updating GCM! I've just also confirmed 11.0.4 works perfectly 🎉

**Comment by de1acr0ix** [comment]
> @de1acr0ix thank you for fixing the Avalonia issue and updating GCM! I've just also confirmed 11.0.4 works perfectly 🎉

There is a change in Avalonia 11 I didn't adopt in this PR. Avalonia 11 can generate `InitializeComponent()` for `.axaml.cs` and fields for named controls. I would rather do it separately in a different PR.

**Pull request merged**
