### PR TITLE
Gitea support

### LINKED ISSUE #145: Add support for Gitea
Add support for Gitea - https://gitea.io/en-us/

### PR DESCRIPTION
**Pull request by hickford**
Fixes #145

tested with https://try.gitea.io/

```sh
git config --global credential.https://try.gitea.io.provider gitea
git config --global credential.https://try.gitea.io.giteadevclientid 7e8fa8b7-1cae-4bc2-beda-2fb982f2113a
git config --global credential.https://try.gitea.io.giteadevclientsecret gto_2hehr5mc7hqvrnxmz2gsl7crzhtu7dypfzpfsx6soch4aliehika
```

### CODE REVIEW

**Comment by hickford** [comment]
Not yet working, fails with OAuth error. Not sure why.

**Comment by hickford** [comment]
Aha Gitea supports Device authorisation grant not the browser one

**Comment by hickford** [comment]
On investigation, I think this is blocked by https://github.com/go-gitea/gitea/issues/21299

**Comment by hickford** [comment]
Fixed problems in Gitea

**Comment by mjcheetham** [comment]
Closing as #1047 added support for adding custom OAuth-based providers via config.

**Pull request closed without merging**
