### PR TITLE
Add first support for Linux arm64

### PR DESCRIPTION
**Pull request by dennisameling**
Currently, trying to install Git Credential Manager Core on Linux arm64 (e.g. WSL2 on the Surface Pro X or Raspberry Pi 4) results in the following error:

```shell
dennis@DESKTOP-8HTP3NV:~/repos$ sudo dpkg -i gmcore.deb
dpkg: error processing archive gmcore.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 gmcore.deb
```
 
This PR adds support for Linux arm64 builds, both when building natively on arm64 or while cross-compiling from an x86 host (in which case you can now run `dotnet build -c LinuxDebug -r linux-arm64`).

Can confirm it works on my arm64 Surface Pro X through WSL2 Ubuntu :tada::

```shell
dennis@DESKTOP-8HTP3NV:~/repos/gmcoretest$ sudo dpkg -i gcmcore-linux_arm64.2.0.301.22928.deb
[sudo] password for dennis:
Selecting previously unselected package gcmcore.
(Reading database ... 40440 files and directories currently installed.)
Preparing to unpack gcmcore-linux_arm64.2.0.301.22928.deb ...
Unpacking gcmcore (2.0.301.22928) ...
Setting up gcmcore (2.0.301.22928) ...
```
```shell
dennis@DESKTOP-8HTP3NV:~/repos/gmcoretest$ git-credential-manager-core --version
Git Credential Manager version 2.0.301-beta+90596ecdf4 (Linux, .NET Core 3.1.10)
```

Things that still need to happen AFAIK:
- Add support for signing multiple `.deb` files at once in `.github/run_esrp_signing.py`, it currently only looks at the first `.deb` file it finds. How does that sound?
- Running tests on arm64. This is possible e.g. with Travis (https://docs.travis-ci.com/user/multi-cpu-architectures/#multi-cpu-availaibility); please let me know if only running tests on amd64 is enough for now or whether you'd like me to set up a Travis config for running tests on arm64 as well.

### CODE REVIEW

**Review by Russgal590 — CHANGES_REQUESTED** [review]
Fix and release from my iPhone 7 Plus and unlock SIM.. thanks

**Review by toot-gerly — APPROVED** [review]

**Comment by toot-gerly** [comment]
Fffffffggghhhhhhhhhhhhhhhhhhhhhhhh

**Comment by hickford** [comment]
If it helps anyone else, here's how I built for 32-bit linux-arm:

https://github.com/GitCredentialManager/git-credential-manager/issues/466#issuecomment-927344088

**Review by firetop0011 — COMMENTED** [review]
dennisameling:add-linux-arm64-compatibility

**Comment by shango420** [comment]
https://api-m.paypal.com/v2/checkout/orders/5O190127TN364715T/capture

**Comment by theofficialgman** [comment]
Any chance on having this updated and merged?

**Comment by mjcheetham** [comment]
Thanks for the contribution. We've since accepted another contributor's PR #1633 that adds both ARM64 and ARM32 support for Linux.

**Pull request closed without merging**
